[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
restartPolicyType = "always"

[environments.production.variables]
NODE_ENV = "production"

# Add persistent volume for SQLite database
[[services]]
name = "dragon-ball-finality"

[services.volumes]
data = "/data"
